import unittest
import sys

# TODO
# fix import system accross package
# seems like test_order called first, appends src to path then subsequent test modules can test src
# individual test module will fail import otherwise
sys.path.append("src")

from src.orders.order import Order, OrderSpec, OrderID
from src.bookkeeping.custom_types import OrderType, ExecutionRule


class TestOrderConstruction(unittest.TestCase):
    def test_remaining_equals_initial_on_init(self): ...
    def test_is_filled_false_on_init(self): ...
    def test_limit_price_accessible(self): ...
    def test_side_accessible(self): ...
    def test_order_type_accessible(self): ...
    def test_execution_rule_accessible(self): ...
    def test_market_order_has_no_limit_price(self): ...
    def test_market_order_has_no_execution_rule(self): ...


class TestOrderFill(unittest.TestCase):
    def test_partial_fill_reduces_remaining(self): ...
    def test_partial_fill_is_not_filled(self): ...
    def test_partial_fill_returns_filled_quantity(self): ...
    def test_full_fill_sets_remaining_to_zero(self): ...
    def test_full_fill_is_filled_true(self): ...
    def test_overfill_clamps_to_zero(self): ...
    def test_overfill_is_filled_true(self): ...
    def test_fill_zero_has_no_effect(self): ...
    def test_fill_zero_returns_zero(self): ...


class TestOrderReduce(unittest.TestCase):
    def test_reduce_updates_remaining(self): ...
    def test_reduce_to_larger_value_raises(self): ...
    def test_reduce_to_equal_value_raises(self): ...


if __name__ == "__main__":
    unittest.main()
