import unittest

from src.orders.factory import OrderFactory, LimitOrderFactory, MarketOrderFactory
from src.orders.order import Order
from src.bookkeeping.custom_types import ExecutionRule, Side


class TestLimitOrderFactory(unittest.TestCase):
    def test_creates_order_with_correct_side(self): ...
    def test_creates_order_with_correct_quantity(self): ...
    def test_creates_order_with_correct_limmit_price(self): ...
    def test_creates_order_with_correct_execution_rule(self): ...
    def test_order_id_assigned_from_generator(self): ...
    def test_sequential_orders_have_different_ids(self): ...
    def test_sequential_orders_ids_are_incrementing(self): ...


class TestMarketOrderFactory(unittest.TestCase):
    def test_creates_order_with_correct_side(self): ...
    def test_creates_order_with_correct_quantity(self): ...
    def test_market_order_has_no_limit_price(self): ...
    def test_market_order_has_no_execution_rule(self): ...
    def test_order_id_assigned_from_generator(self): ...


class TestFactoriesShareGenerator(unittest.TestCase):
    def test_limit_and_market_ids_do_not_collide(self): ...
